-- 既存プロジェクトへ password_resets を足す（#47）。
-- Supabase の SQL Editor に貼って Run する。schema.sql を全部流しても同じ。

create table if not exists password_resets (
  id integer generated by default as identity primary key,
  user_id integer not null references auth_users (id) on delete cascade,
  token text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null
);

create index if not exists ix_password_resets_user_id on password_resets (user_id);

alter table password_resets enable row level security;
revoke all on table password_resets from anon, authenticated;
