-- PaceCast 用 PostgreSQL スキーマ（Supabase SQL Editor に貼る）。
-- 認証はアプリ独自（Cookie + PBKDF2）。Supabase Auth は使わない。
-- 画面の API は service_role のみでアクセスする。anon は RLS で拒否する。

create extension if not exists pgcrypto;

create table if not exists auth_users (
  id integer generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  email_verified boolean not null default false,
  created_at timestamptz not null
);

create table if not exists email_verifications (
  id integer generated by default as identity primary key,
  user_id integer not null references auth_users (id) on delete cascade,
  token text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null
);

create table if not exists password_resets (
  id integer generated by default as identity primary key,
  user_id integer not null references auth_users (id) on delete cascade,
  token text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null
);

create table if not exists weather_observations (
  id integer generated by default as identity primary key,
  observed_at timestamptz not null,
  location text not null,
  temperature_c double precision not null,
  humidity_pct double precision not null,
  temperature_quality integer,
  humidity_quality integer,
  wind_ms double precision,
  solar_wm2 double precision,
  wbgt_c double precision,
  wbgt_method text,
  station_id text,
  source text not null default 'open-meteo',
  imported_at timestamptz not null
);

create unique index if not exists uq_weather_observed_station
  on weather_observations (observed_at, coalesce(station_id, ''));

create index if not exists ix_weather_observed_at
  on weather_observations (observed_at);

create table if not exists user_profiles (
  id integer generated by default as identity primary key,
  auth_user_id integer unique references auth_users (id) on delete cascade,
  display_name text,
  birthday date,
  max_heart_rate integer,
  color_rows boolean not null default true,
  row_color_mode text not null default 'hr',
  hr_low integer,
  hr_medium integer,
  hr_high integer,
  hr_race_5k integer,
  hr_race_10k integer,
  hr_race_half integer,
  hr_race_full integer,
  amedas_station_id text,
  amedas_station_name text,
  run_station_init text not null default 'profile',
  updated_at timestamptz not null
);

create table if not exists running_records (
  id integer generated by default as identity primary key,
  started_at timestamptz not null,
  distance_km double precision not null,
  duration_sec integer not null,
  avg_heart_rate integer,
  notes text,
  amedas_station_id text,
  amedas_station_name text,
  auth_user_id integer references auth_users (id) on delete cascade,
  weather_observation_id integer references weather_observations (id) on delete set null,
  weather_end_observation_id integer references weather_observations (id) on delete set null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create index if not exists ix_runs_started_at on running_records (started_at);
create index if not exists ix_runs_auth_user_id on running_records (auth_user_id);
create index if not exists ix_runs_weather_id on running_records (weather_observation_id);
create index if not exists ix_runs_weather_end_id on running_records (weather_end_observation_id);
create index if not exists ix_verifications_user_id on email_verifications (user_id);
create index if not exists ix_password_resets_user_id on password_resets (user_id);

alter table auth_users enable row level security;
alter table email_verifications enable row level security;
alter table password_resets enable row level security;
alter table weather_observations enable row level security;
alter table user_profiles enable row level security;
alter table running_records enable row level security;

revoke all on table auth_users from anon, authenticated;
revoke all on table email_verifications from anon, authenticated;
revoke all on table password_resets from anon, authenticated;
revoke all on table weather_observations from anon, authenticated;
revoke all on table user_profiles from anon, authenticated;
revoke all on table running_records from anon, authenticated;

create or replace function reset_id_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  max_id integer;
begin
  select max(id) into max_id from auth_users;
  if max_id is null then
    perform setval(pg_get_serial_sequence('auth_users', 'id'), 1, false);
  else
    perform setval(pg_get_serial_sequence('auth_users', 'id'), max_id, true);
  end if;

  select max(id) into max_id from email_verifications;
  if max_id is null then
    perform setval(pg_get_serial_sequence('email_verifications', 'id'), 1, false);
  else
    perform setval(pg_get_serial_sequence('email_verifications', 'id'), max_id, true);
  end if;

  select max(id) into max_id from password_resets;
  if max_id is null then
    perform setval(pg_get_serial_sequence('password_resets', 'id'), 1, false);
  else
    perform setval(pg_get_serial_sequence('password_resets', 'id'), max_id, true);
  end if;

  select max(id) into max_id from weather_observations;
  if max_id is null then
    perform setval(pg_get_serial_sequence('weather_observations', 'id'), 1, false);
  else
    perform setval(pg_get_serial_sequence('weather_observations', 'id'), max_id, true);
  end if;

  select max(id) into max_id from user_profiles;
  if max_id is null then
    perform setval(pg_get_serial_sequence('user_profiles', 'id'), 1, false);
  else
    perform setval(pg_get_serial_sequence('user_profiles', 'id'), max_id, true);
  end if;

  select max(id) into max_id from running_records;
  if max_id is null then
    perform setval(pg_get_serial_sequence('running_records', 'id'), 1, false);
  else
    perform setval(pg_get_serial_sequence('running_records', 'id'), max_id, true);
  end if;
end;
$$;

revoke all on function reset_id_sequences() from public, anon, authenticated;
grant execute on function reset_id_sequences() to service_role;
